version: '3.8'
services:
    simple-cms-backend:
        image: lst97/simple-cms-backend:dev
        ports:
            - '1168:1168'
        expose:
            - '1168'
        depends_on:
            - mongo
        volumes:
            - ~/app:/app:ro
        networks:
            - app-network

    mongo:
        image: arm64v8/mongo:4.4.18
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data:
